Cloud deployment
Incorta/OpenCopilot pull request #24
Opened 2023-09-12 12:08 UTC by HaniaMoHani

Modified some namings

2023-09-14 07:35 UTC, oabdelkarim requested changes

2023-09-14 07:35 UTC, oabdelkarim commented on opencopilot/utils/langchain/llm_GPT.py
> +            engine="gpt4-model" if model == LLMModelName.azure_openai_gpt_4.value else "gpt35-model",
Either model or engine are constants. Review Azure docs and remove the one that is constant from here and use it directly a constant in the code

2023-09-14 14:14 UTC, oabdelkarim commented on opencopilot/utils/langchain/llm_GPT.py
> +            engine=llm_configs[model]["api_deployment_name"],
I don't think this is required either. Engine is not configurable, it is a fixed value for gpt_4 and for gpt_35_turbo (and any model) on OpenAI. Deployment is configurable and required in Azure only because we first create a deployment on Azure platform with some name then set the model from OpenAI to be deployed on it.

2023-09-17 10:10 UTC, merged

2023-09-17 15:53 UTC, OmarWAboZeid commented on opencopilot/utils/langchain/llm_GPT.py
> +            engine=llm_configs[model]["api_deployment_name"],
Engine is Optional configurations which is a string specifying the model to use (e.g. "davinci"). default is "davinci" which maps to GPT3.5.