Feat/persistant logging system
Incorta/OpenCopilot pull request #37
Opened 2023-11-27 10:30 UTC by Basem-Gaber

2023-11-28 18:18 UTC, oabdelkarim requested changes

2023-11-28 18:18 UTC, oabdelkarim commented on opencopilot/utils/logger.py
> +__internal_logger = setup_logger()
Will this be called in every import?

2023-11-28 18:18 UTC, oabdelkarim commented on opencopilot/utils/logger.py
> +    log_level_str = os.environ.get("COPILOT_LOG_LEVEL", "INFO")
Let the default be the least one, not the most verbose one. That way, if not set by mistake, the logs won't explode

2023-11-28 18:18 UTC, oabdelkarim commented on opencopilot/utils/logger.py
> +    log_file = 'logs/app.log'
We need to make this variable. Not only the file name but the whole mechanims. That way, through the configs, one can set the logger like:

`logging.basicConfig(stream=sys.stdout, level=logging.INFO)`

We can also make it so along with the rotating handler in the configs. The configs are python, so we can intialize the handler there to give freedom for other users of the system to customize it through the configs file or even use stdout/error as above

2023-11-28 18:32 UTC, oabdelkarim commented on opencopilot/utils/logger.py
> +__internal_logger = setup_logger()
I am not sure whether "add_handler" will keep adding handlers on every call or not! Let us be in the safe side and make sure not to call it if internal_logger is already set

2023-12-03 15:32 UTC, Basem-Gaber commented on opencopilot/utils/logger.py
> +__internal_logger = setup_logger()
Done

2023-12-03 15:32 UTC, Basem-Gaber commented on opencopilot/utils/logger.py
> +    log_file = 'logs/app.log'
Discussed and decided to not do

2023-12-03 15:34 UTC, merged